### ISSUE TITLE
In configuration files, enable values to be grabbed from environment variables

### ISSUE THREAD

**Issue by oveddan** [sinatra/sinatra-contrib#116]
In many situations, it is ideal to grab a configuration value from an environment variable.

Right now, this is not possible with config_file

Try, for example, to do this:

```yaml
  development: 
    database_connection: "localhost:9999/some_db_connection"

  production:
    database_connection: <%= ENV['DB_CONNECTION'] %>
```

In the app, if you are in a production environment, when you do 

```ruby
  settings.database_connection 
```

you get:

"<%= ENV['DB_CONNECTION'] %>"
